version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: s7fC-Qc8hg-5wKm-An3x
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  seed:
    build: .
    command: python ./seed.py
    depends_on:
      - postgres

